(()=>{
  if(window.__premiumTripLoaded)return; window.__premiumTripLoaded=true;
  const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
  const hero=q('.hero'),sw=q('.switch'); if(!hero||!sw)return;
  const flagHtml={three:'<span class="routeFlag flagHU" title="הונגריה"></span><span class="routeFlag flagAT" title="אוסטריה"></span><span class="routeFlag flagSI" title="סלובניה"></span>',two:'<span class="routeFlag flagHU" title="הונגריה"></span><span class="routeFlag flagSI" title="סלובניה"></span>'};
  const miniFlagHtml={three:'<span class="miniFlags"><i class="miniFlag flagHU"></i><i class="miniFlag flagAT"></i><i class="miniFlag flagSI"></i></span>',two:'<span class="miniFlags"><i class="miniFlag flagHU"></i><i class="miniFlag flagSI"></i></span>'};
  const routeNames={three:'הונגריה · אוסטריה · סלובניה',two:'הונגריה · סלובניה'};

  qa('a').forEach(a=>{if((a.textContent||'').includes('האתר הקודם')){a.href='legacy-index.html';a.target='_top'}});
  if(!q('.legacyTab',sw)){const a=document.createElement('a');a.className='legacyTab';a.href='legacy-index.html';a.target='_top';a.textContent='🧰 האתר הקודם';sw.appendChild(a)}

  let h1=q('h1',hero); if(h1){h1.id='routeHeroTitle';h1.innerHTML='<span id="routeHeroFlags"></span><span id="routeHeroName"></span>'}
  if(!q('.heroTop',hero)){const top=document.createElement('div');top.className='heroTop';const kicker=q('.tiny',hero);if(kicker)top.appendChild(kicker);hero.insertBefore(top,hero.firstChild)}
  if(h1&&!q('.designHint',hero)){const hint=document.createElement('div');hint.className='designHint';hint.textContent='מסע משפחתי · אגמים, הרים, מערות ורגעים קטנים';h1.insertAdjacentElement('afterend',hint)}

  const tabs=qa('.switch .tab').slice(0,2);tabs.forEach((b,i)=>{const r=i===0?'three':'two';b.dataset.route=r;b.innerHTML=miniFlagHtml[r]+(r==='three'?'חלופה A — 3 מדינות':'חלופה B — 2 מדינות')});
  function currentRoute(){const a=tabs.find(b=>b.classList.contains('active'));return a?.dataset.route||localStorage.getItem('tripRoute2026')||'three'}
  function syncRoute(route){if(!routeNames[route])route='three';const f=q('#routeHeroFlags'),n=q('#routeHeroName');if(f)f.innerHTML=flagHtml[route];if(n)n.textContent=routeNames[route];document.body.dataset.route=route;try{localStorage.setItem('tripRoute2026',route)}catch(e){};renderTomorrow();renderKidQuest(route)}
  tabs.forEach(b=>b.addEventListener('click',()=>setTimeout(()=>syncRoute(b.dataset.route),0)));syncRoute(currentRoute());

  if(!q('[data-budget-route="three"]')){
    const budgetMarkup=route=>`<section class="budgetPanel" data-budget-route="${route}"><div class="budgetHead"><div><h3>💰 תקציב החלופה</h3><p>הנתונים נשמרים אוטומטית במכשיר הזה ונפרדים לכל חלופה.</p></div><div class="budgetTotal" data-budget-total>₪0</div></div><div class="budgetGrid">${[['flights','✈️ טיסות'],['hotels','🏨 לינה'],['car','🚗 רכב שכור'],['road','⛽ דלק / אגרות / חניה'],['attractions','🎟️ אטרקציות'],['food','🍽️ אוכל'],['shopping','🛍️ קניות'],['other','➕ שונות']].map(([k,l])=>`<label class="budgetItem"><span>${l}</span><input type="number" min="0" step="50" inputmode="decimal" data-budget-key="${k}" placeholder="0"></label>`).join('')}</div><div class="budgetFoot"><span>סה״כ מתעדכן בזמן אמת.</span><button class="budgetReset" type="button" data-budget-reset>איפוס תקציב</button></div></section>`;
    const mapThree=`<section class="schematic"><div class="schematicHead"><div><h3>🧭 מפה סכמטית — חלופה A · 3 מדינות</h3><small>בודפשט → בלטון → קרינתיה → סלובניה → בודפשט</small></div><small>לא בקנה מידה</small></div><div class="schematicScroll"><svg viewBox="0 0 1040 250"><path class="path" d="M80 130 C170 65 245 75 320 120 S470 190 555 120 S720 50 795 115 S915 175 965 125"/><circle class="node major" cx="80" cy="130" r="13"/><text class="lbl" x="80" y="105">בודפשט</text><circle class="node" cx="300" cy="112" r="12"/><text class="lbl" x="300" y="82">בלטון</text><circle class="node" cx="540" cy="127" r="12"/><text class="lbl" x="540" y="96">קרינתיה</text><circle class="node" cx="770" cy="105" r="12"/><text class="lbl" x="770" y="74">בלד</text><circle class="node" cx="900" cy="150" r="12"/><text class="lbl" x="900" y="184">Maribor</text><circle class="node major" cx="965" cy="125" r="13"/><text class="lbl" x="965" y="96">בודפשט</text></svg></div></section>`;
    const mapTwo=`<section class="schematic"><div class="schematicHead"><div><h3>🧭 מפה סכמטית — חלופה B · הונגריה–סלובניה</h3><small>בודפשט → בלטון → בלד והאלפים היוליאניים → Maribor/Ptuj → בודפשט</small></div><small>לא בקנה מידה</small></div><div class="schematicScroll"><svg viewBox="0 0 1040 250"><path class="path" d="M80 130 C180 70 260 80 345 128 S520 175 625 105 S805 75 880 135 S940 155 965 125"/><circle class="node major" cx="80" cy="130" r="13"/><text class="lbl" x="80" y="105">בודפשט</text><circle class="node" cx="320" cy="120" r="12"/><text class="lbl" x="320" y="90">בלטון</text><circle class="node" cx="610" cy="112" r="12"/><text class="lbl" x="610" y="82">בלד</text><circle class="node" cx="845" cy="125" r="12"/><text class="lbl" x="845" y="94">Maribor / Ptuj</text><circle class="node major" cx="965" cy="125" r="13"/><text class="lbl" x="965" y="96">בודפשט</text></svg></div></section>`;
    [['three',mapThree],['two',mapTwo]].forEach(([route,map])=>{const pane=q('#'+route),overview=pane&&q('.grid.cols2',pane);if(overview)overview.insertAdjacentHTML('afterend',map+budgetMarkup(route))});
  }
  const fmt=new Intl.NumberFormat('he-IL',{style:'currency',currency:'ILS',maximumFractionDigits:0});qa('[data-budget-route]').forEach(box=>{if(box.dataset.ready)return;box.dataset.ready='1';const route=box.dataset.budgetRoute,key='tripBudget2026:'+route;let saved={};try{saved=JSON.parse(localStorage.getItem(key)||localStorage.getItem('tripBudget2026_'+route)||'{}')}catch(e){};const inputs=qa('[data-budget-key]',box);inputs.forEach(i=>{if(saved[i.dataset.budgetKey]!=null)i.value=saved[i.dataset.budgetKey]||''});const update=()=>{let total=0,state={};inputs.forEach(i=>{const v=Math.max(0,Number(i.value)||0);state[i.dataset.budgetKey]=v;total+=v});localStorage.setItem(key,JSON.stringify(state));q('[data-budget-total]',box).textContent=fmt.format(total)};inputs.forEach(i=>i.addEventListener('input',update));q('[data-budget-reset]',box)?.addEventListener('click',()=>{inputs.forEach(i=>i.value='');update()});update()});

  let alert=q('.alert');if(alert){alert.className='tomorrowBrief';alert.id='tomorrowBrief';alert.innerHTML='<div class="tomorrowInner"><div class="tomorrowIcon">🧭</div><div><div class="tomorrowEyebrow">העדכון המרכזי למחר <span class="tomorrowDate" id="tomorrowDate"></span></div><div class="tomorrowTitle" id="tomorrowTitle">טוען את היום הבא…</div><div class="tomorrowText" id="tomorrowText"></div><div class="weatherLine" id="weatherLine"></div><div class="tomorrowCredit" id="tomorrowCredit"></div></div><div class="tomorrowActions"><a id="tomorrowMap" target="_blank">🗺️ מסלול</a></div></div>'}
  const coordsFor=x=>{const s=(x.title+' '+x.region).toLowerCase();if(s.includes('gerlitzen')||s.includes('ossiach'))return[46.69,13.91];if(s.includes('malta')||s.includes('kölnbrein'))return[47.08,13.40];if(s.includes('bohinj')||s.includes('vogel'))return[46.275,13.835];if(s.includes('jasna')||s.includes('planica')||s.includes('kranjska'))return[46.485,13.786];if(s.includes('velika'))return[46.297,14.642];if(s.includes('postojna')||s.includes('predjama'))return[45.774,14.214];if(s.includes('ljubljana'))return[46.056,14.505];if(s.includes('maribor')||s.includes('ptuj'))return[46.554,15.646];if(s.includes('balaton')||s.includes('tihany'))return[46.96,17.89];if(s.includes('budapest')||s.includes('בודפשט'))return[47.498,19.04];return[46.369,14.113]};
  const wmo=c=>c===0?'☀️ בהיר':c<=3?'⛅ מעונן חלקית':c<=48?'🌫️ ערפילי':c<=67?'🌧️ גשם':c<=77?'🌨️ שלג':c<=82?'🌦️ ממטרים':'⛈️ סופות';
  const parseDate=(x,year)=>{const m=(x.date||'').match(/(\d{2})\/(\d{2})/);return m?new Date(year,Number(m[2])-1,Number(m[1]),12):null};
  async function addWeather(x,date){const line=q('#weatherLine');if(!line)return;line.innerHTML='<span class="weatherChip">🌦️ טוען תחזית למחר…</span>';const [lat,lon]=coordsFor(x),iso=date.toISOString().slice(0,10);try{const u=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,wind_speed_10m_max&timezone=auto&start_date=${iso}&end_date=${iso}`;const r=await fetch(u);if(!r.ok)throw 0;const j=await r.json(),d=j.daily;line.innerHTML=`<span class="weatherChip">${wmo(d.weather_code[0])}</span><span class="weatherChip">🌡️ ${Math.round(d.temperature_2m_min[0])}°–${Math.round(d.temperature_2m_max[0])}°</span><span class="weatherChip">💧 ${Math.round(d.precipitation_probability_max[0]||0)}%</span><span class="weatherChip">💨 עד ${Math.round(d.wind_speed_10m_max[0]||0)} קמ״ש</span>`;q('#tomorrowCredit').textContent='תחזית: Open‑Meteo · יש לבדוק שוב בבוקר, במיוחד בימי הרים ורכבלים.'}catch(e){line.innerHTML='<span class="weatherChip">🌦️ התחזית לא נטענה — בדקו שוב מאוחר יותר</span>';q('#tomorrowCredit').textContent='בימי הרים ורכבלים יש לאמת תפעול וראות בבוקר.'}}
  function renderTomorrow(){if(!alert||typeof three==='undefined'||typeof two==='undefined')return;const route=currentRoute(),arr=route==='two'?two:three,now=new Date(),year=now.getFullYear(),tom=new Date(year,now.getMonth(),now.getDate()+1,12);const dates=arr.map(x=>[x,parseDate(x,year)]).filter(x=>x[1]);let x=dates.find(v=>v[1].toDateString()===tom.toDateString())?.[0],target=tom,label='מחר';if(!x){const first=dates[0],last=dates[dates.length-1];if(first&&tom<first[1]){x=first[0];target=first[1];label='הכנה ליום הראשון'}else if(last&&tom>last[1]){q('#tomorrowDate').textContent='';q('#tomorrowTitle').textContent='הטיול הסתיים — איזה מסע!';q('#tomorrowText').textContent='התקדמות משחק החיות והתקציב נשארים שמורים במכשיר.';q('#weatherLine').innerHTML='';q('#tomorrowMap').style.display='none';return}else{x=arr[0];target=parseDate(x,year)}}q('#tomorrowMap').style.display='inline-flex';q('#tomorrowDate').textContent=`${label} · ${new Intl.DateTimeFormat('he-IL',{weekday:'long',day:'2-digit',month:'2-digit'}).format(target)}`;q('#tomorrowTitle').textContent=`יום ${x.d}: ${x.title}`;const first=x.sched?.[0]?`פתיחה: ${x.sched[0][0]} — ${x.sched[0][1]}. `:'';q('#tomorrowText').textContent=first+(x.rec||'')+' '+(x.note||'');q('#tomorrowMap').href=x.map||'#';q('.tomorrowIcon').textContent=(x.title.includes('Vogel')||x.title.includes('Gerlitzen')||x.title.includes('Velika')||x.title.includes('Malta'))?'🏔️':x.title.includes('Cave')||x.title.includes('Postojna')?'🕳️':x.title.includes('Budapest')||x.title.includes('בודפשט')?'🏙️':x.title.includes('Bled')||x.title.includes('Bohinj')?'🌊':'🧭';addWeather(x,target)}

  const animals=['🦊','🐼','🦁','🐬','🦒','🐘','🦉','🐧','🐨','🦋','🐢','🦄','🐯','🐻'];
  const pkey=(r,d)=>`tripKid2026:${r}:${d}`;const load=(r,d,n)=>{let a=[];try{a=JSON.parse(localStorage.getItem(pkey(r,d))||'[]')}catch(e){};return Array.from({length:n},(_,i)=>!!a[i])};const save=(r,d,a)=>localStorage.setItem(pkey(r,d),JSON.stringify(a));
  function addQuest(route){const pane=q('#'+route);if(!pane)return;const days=qa('.day',pane);const heading=[...pane.querySelectorAll('h2')].find(h=>(h.textContent||'').includes('מסלול יום'));if(heading&&!q('.kidQuest',pane)){const box=document.createElement('div');box.className='kidQuest';box.dataset.kidRoute=route;heading.insertAdjacentElement('afterend',box)}days.forEach((dayEl,idx)=>{const day=Number(q('.num',dayEl)?.textContent)||idx+1;dayEl.dataset.questRoute=route;dayEl.dataset.questDay=day;const rows=qa('.schedule .row',dayEl);if(!rows.length)return;const summary=q('summary',dayEl),meta=q('.meta',summary);if(meta&&!q('.dayProgress',summary))meta.insertAdjacentHTML('afterend',`<div class="dayProgress"><div class="dayProgressBar"><i></i></div><span class="dayProgressText">0/${rows.length}</span></div>`);rows.forEach((row,i)=>{if(row.classList.contains('taskRow'))return;row.classList.add('taskRow');row.dataset.task=i;const txt=row.children[1];if(txt)txt.classList.add('taskText');row.insertAdjacentHTML('beforeend','<div class="taskCheck" aria-label="סימון משימה">✓</div>');row.tabIndex=0;row.addEventListener('click',()=>toggleTask(row));row.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggleTask(row)}})});const body=q('.body',dayEl);if(body&&!q('.dayReward',body)){const note=q('.note',body);const reward=document.createElement('div');reward.className='dayReward';reward.innerHTML=`<span class="rewardAnimal">${animals[(day-1)%animals.length]}</span><span><b>חיית היום:</b> השלימו את כל התחנות כדי לצרף אותה לאוסף.</span>`;(note||body.firstChild).insertAdjacentElement(note?'beforebegin':'afterend',reward)}updateDay(dayEl)})}
  function updateDay(dayEl){const r=dayEl.dataset.questRoute,d=Number(dayEl.dataset.questDay),rows=qa('.taskRow',dayEl),state=load(r,d,rows.length);let done=0;rows.forEach((row,i)=>{row.classList.toggle('complete',state[i]);if(state[i])done++});q('.dayProgressBar i',dayEl).style.width=(rows.length?100*done/rows.length:0)+'%';q('.dayProgressText',dayEl).textContent=`${done}/${rows.length}`;dayEl.classList.toggle('done',rows.length>0&&done===rows.length);return rows.length>0&&done===rows.length}
  function toggleTask(row){const dayEl=row.closest('.day'),r=dayEl.dataset.questRoute,d=Number(dayEl.dataset.questDay),rows=qa('.taskRow',dayEl),state=load(r,d,rows.length),was=state.every(Boolean),i=Number(row.dataset.task);state[i]=!state[i];save(r,d,state);const now=updateDay(dayEl);renderKidQuest(r);if(now&&!was)celebrate(d)}
  function renderKidQuest(route){const pane=q('#'+route),box=pane&&q('.kidQuest',pane);if(!box)return;const days=qa('.day',pane);let earned=0;const badges=days.map((el,idx)=>{const d=Number(el.dataset.questDay)||idx+1,rows=qa('.taskRow',el),on=rows.length&&load(route,d,rows.length).every(Boolean);if(on)earned++;return `<span class="animalBadge ${on?'earned':''}" title="יום ${d}">${animals[(d-1)%animals.length]}</span>`}).join('');box.innerHTML=`<div class="kidHead"><div><h3>🐾 מסע החיות של הילד</h3><p>מסמנים כל תחנה שסיימתם. כשכל משימות היום הושלמו — חיית היום מצטרפת לאוסף.</p></div><div class="kidProgress">${earned}/${days.length} חיות נאספו</div></div><div class="animalShelf">${badges}</div>`}
  function celebrate(day){let c=q('#celebration');if(!c){c=document.createElement('div');c.id='celebration';c.className='celebration';c.innerHTML='<div class="celebrateCard"><div class="celebrateAnimal" id="celebrateAnimal"></div><h3 id="celebrateTitle"></h3><p>סיימתם את כל משימות היום. חיית היום הצטרפה לאוסף המסע!</p><button type="button">ממשיכים להרפתקה ✨</button></div>';document.body.appendChild(c);q('button',c).onclick=()=>c.classList.remove('show')}q('#celebrateAnimal',c).textContent=animals[(day-1)%animals.length];q('#celebrateTitle',c).textContent=`כל הכבוד! יום ${day} הושלם`;c.classList.add('show');const colors=['#efc56d','#63b98b','#69a7d6','#ef8b7b','#aa8ed6'];for(let i=0;i<28;i++){const p=document.createElement('i');p.className='confettiPiece';p.style.left=Math.random()*100+'vw';p.style.background=colors[i%colors.length];p.style.setProperty('--x',(Math.random()*180-90)+'px');p.style.animationDelay=Math.random()*.35+'s';document.body.appendChild(p);setTimeout(()=>p.remove(),2300)}}
  addQuest('three');addQuest('two');renderKidQuest('three');renderKidQuest('two');renderTomorrow();

  const io='IntersectionObserver'in window?new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08}):null;qa('.card,.schematic,.budgetPanel,.kidQuest,.day').forEach(el=>{el.classList.add('revealPremium');if(io)io.observe(el);else el.classList.add('visible')});
})();
